# build process in order to produce the PDF file of the guide
name: Compile LuaLaTeX main file guidalua.tex
on:
  push:
    tags:
      - 'v*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: 🦁 Compile LuaLaTeX document
        run: |
          lualatex --shell-escape guidalua
          biber guidalua
          lualatex --shell-escape guidalua
          lualatex --shell-escape guidalua
          mkdir assets
          mv guidalua.pdf assets/guidalua.pdf
      - name: 🎉 Release
        uses: softprops/action-gh-release@v1
        with:
          files: guidalua.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 📂 Upload via ftp the PDF file
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./assets"
          server-dir: "/httpdocs/home/images/doc/GuideGuIT"
          security: "strict"
