# This is a basic workflow to help you get started with Actions

name: Build LuaLaTeX guide

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LuaLaTeX document i
        uses: dante-ev/latex-action@master
        with:
          compiler: lualatex
          args: --shell-escape
          root_file: guidalua.tex
      - name: Compile LuaLaTeX document ii
        uses: dante-ev/latex-action@master
        with:
          compiler: lualatex
          args: --shell-escape
          root_file: guidalua.tex
      - uses: actions/upload-artifact@v2
        with:
          name: guidalua
          path: guidalua.pdf
    
