# build process in order to produce the PDF file of the guide
name: Compile LuaLaTeX main file guidalua.tex
on:
  push:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LuaLaTeX document
        run: |
          lualatex --shell-escape guidalua
          biber guidalua
          lualatex --shell-escape guidalua
          lualatex --shell-escape guidalua

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: guidalua.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
